### PR TITLE
Updated run-functional-tests.sh

### PR DESCRIPTION
**Pull request by aputriax**
Added options:
- SAI Server IP address
- Paths to port map and port config files
- Underlay/Overlay tests selection
- Hardware/BMv2 selection
- Interfaces specifing

Signed-off-by: Yuriy Harhas <yuriyx.harhas@intel.com>

### CODE REVIEW

**Comment by chrispsommers** [comment]
I suggest you consider to rename/move this script to `test/test-cases/functional/ptf/run-tests.sh` and the test path would nominally be `.` I am contemplating doing the same for saic tests under `functional/` and `scale/`

**Comment by aputriax** [comment]
> I suggest you consider to rename/move this script to `test/test-cases/functional/ptf/run-tests.sh` and the test path would nominally be `.` I am contemplating doing the same for saic tests under `functional/` and `scale/`

I can do this, but than I'll need to update Makefile as well. If it is ok, I'll update this PR.

**Comment by chrispsommers** [comment]
> > I suggest you consider to rename/move this script to `test/test-cases/functional/ptf/run-tests.sh` and the test path would nominally be `.` I am contemplating doing the same for saic tests under `functional/` and `scale/`
> 
> I can do this, but than I'll need to update Makefile as well. If it is ok, I'll update this PR.

Updating the Makefile is fine by me, thanks.

**Review by chrispsommers — APPROVED** [review]
LGTM

**Review by chrispsommers — APPROVED** [review]
LGTM

**Pull request merged**
