### PR TITLE
Fixbug: SAI Server crash on DASH ACL API

### PR DESCRIPTION
**Pull request by Pterosaur**
1. Fix duplicate SAI ID
2. Wrong search action
3. Double delete entry if SAI write error
4. Wrong format of error message

Signed-off-by: Ze Gan <ganze718@gmail.com>

### CODE REVIEW

**Comment by chrispsommers** [comment]
Thanks for this PR. It would be really nice to add some PTF test-cases. How do we know this fixes a problem? Thanks.

**Comment by Pterosaur** [comment]
> Thanks for this PR. It would be really nice to add some PTF test-cases. How do we know this fixes a problem? Thanks.

@chrispsommers I found these issues when I'm developing ACL DASH TEST. I will submit another PR for some testcases.

**Comment by chrispsommers** [comment]
> > Thanks for this PR. It would be really nice to add some PTF test-cases. How do we know this fixes a problem? Thanks.
> 
> @chrispsommers I found these issues when I'm developing ACL DASH TEST. I will submit another PR for some testcases.

Hi Ze, actually it'd be preferable (not mandatory though) if you could add test cases to this PR. I would be happy to try them out.

**Comment by lguohan** [comment]
@marian-pritsak , can you take a look at these fixes?

**Comment by lguohan** [comment]
@chrispsommers , can you setup CI to run those ptf test automatically?

**Comment by Pterosaur** [comment]
> @chrispsommers , can we setup CI to run those ptf test automatically?

Hi Guohan, I think the PTF test have been added to the CI,
DASH-BMV2-CI / Build and Test DASH Pipeline (pull_request).

**Comment by Pterosaur** [comment]
> > > Thanks for this PR. It would be really nice to add some PTF test-cases. How do we know this fixes a problem? Thanks.
> > 
> > 
> > @chrispsommers I found these issues when I'm developing ACL DASH TEST. I will submit another PR for some testcases.
> 
> Hi Ze, actually it'd be preferable (not mandatory though) if you could add test cases to this PR. I would be happy to try them out.

Sure, I add a simplest ptf test, calling few dash acl SAI APIs. If without this PR, the saiserver will crash after these SAI API.

Meanwhile, I found some other bugs in the implementation of DASH ACL, but need more time to fix and polish them. So, another PR will include fixing bugs and their testcases.

**Comment by chrispsommers** [comment]
> > @chrispsommers , can we setup CI to run those ptf test automatically?
> 
> Hi Guohan, I think the PTF test have been added to the CI, DASH-BMV2-CI / Build and Test DASH Pipeline (pull_request).

@guohan, @Pterosaur Indeed, the test was already in place. Ze just uncommented the ACL setup/teardown code which had been failing. The test is now passing in the CI pipeline, for example: https://github.com/Azure/DASH/actions/runs/3328179677/jobs/5503875075#step:17:1

**Review by chrispsommers — APPROVED** [review]
LGTM

**Review by mukeshmv — APPROVED** [review]
lgtm. 
Also I had raised a Dash bmv2 ACL implementation issue here 
https://github.com/Azure/DASH/issues/232

**Pull request merged**
