### PR TITLE
mm-dash-test-wflow-saithrift 

### PR DESCRIPTION
**Pull request by mmiele**
Created DASH test workflow with saithrift

### CODE REVIEW

**Review by KrisNey-MSFT — COMMENTED** [review]
If I were someone just learning the flow, @chrispsommers  - I would wonder what is the difference between the GitHub starting point icon, and the one below it that says Sirius P4 behavioral model.  Are both supposed to start in parallel?  Maybe we could figure out a way to clearly show Step 1, Step 2, etc... we can get together tomorrow?

**Comment by chrispsommers** [comment]
@KrisNey-MSFT We can clarify it by replacing the "start" label with "input" and drawing another dotted line showing the sirius.p4 model coming from GitHub. I plan on writing copy for this shortly.

**Comment by chrispsommers** [comment]
@mmiele  LGTM - ready for a squash-merge, thanks!

**Comment by KrisNey-MSFT** [comment]
Ready to merge

**Pull request merged**
