### PR TITLE
Remove inbound VM table

### PR DESCRIPTION
**Pull request by marian-pritsak**
Map ENI to PA directly

Signed-off-by: Marian Pritsak <marianp@mellanox.com>

### CODE REVIEW

**Comment by chrispsommers** [comment]
Hi @marian-pritsak I'd prefer that we merge https://github.com/Azure/DASH/pull/127 first, which will would require a subsequent sync on your part, hopefully not too painful. The advantage of doing it in this order is we'll get to try the CI pipeline; it should trigger when you push to your dev branch since it's part of a PR.

**Comment by chrispsommers** [comment]
Hi @marian-pritsak, PR](https://github.com/Azure/DASH/pull/127) was merged (plus a couple follow-ups to fix stray CI issues) so you can proceed. The CI pipeline should trigger on your P4 code change.

**Review by chrispsommers — APPROVED** [review]
LGTM

**Review by prsunny — APPROVED** [review]
lgtm, related SAI PR merged - https://github.com/opencomputeproject/SAI/pull/1516

**Pull request merged**
