### PR TITLE
Dash ENI create/remove tests

### PR DESCRIPTION
**Pull request by aputriax**
- Added ENI verification test plan.
- Added automated ENI tests.
- Moved all common functions to sai_dash_utils.py
- Skipped failing tests on CI.

### CODE REVIEW

**Comment by KrisNey-MSFT** [comment]
Making a separate file for common functions for ease of review (see only 2 files).

**Comment by aputriax** [comment]
> Making a separate file for common functions for ease of review (see only 2 files).

Done. Common functions are already merged in PR #298. So this PR now contains only 2 files.

**Review by chrispsommers — APPROVED** [review]
LGTM

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
lgtm, we can add more cases on top of this as future commits

**Comment by prsunny** [comment]
@theasianpianist for viz

**Pull request merged**
